### ISSUE TITLE
Employee

### ISSUE THREAD

**Issue by eduardomrodrigues** [cubcoffee/valhalla-api#9]
- [x] Create and persist employee entity - #30 
- [x] Find employee by ID - #37 
- [ ] Update employee -  #38
- [x] Remove employee by ID - #39
